apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-latest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app
      version: latest
  template:
    metadata:
      labels:
        app: web-app
        version: latest
    spec:
      containers:
      - name: web-app-container
        image: eywrld839/webapp:arg
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 5000
      protocol: TCP
  selector:
    app: web-app
