apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dev
  namespace: dev
  labels:
    COLOR: "{{ .Env.COLOR }}"
  annotations:
    COLOR: "{{ .Env.COLOR }}"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app-dev
      version: dev
  template:
    metadata:
      labels:
        app: web-app-dev
        version: dev
        COLOR: "{{ .Env.COLOR }}"
      annotations:
        COLOR: "{{ .Env.COLOR }}"
    spec:
      containers:
      - name: web-app-container
        image: eywrld839/webapp:devaa
        env:
        - name: COLOR
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['color']
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: web-app-dev
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: prod
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: web-app-prod
