apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-prod
      version: latest
  template:
    metadata:
      labels:
        app: web-app-prod
        version: latest
    spec:
      containers:
      - name: web-app-container
        image: eywrld839/webapp:latest
        env:
          - name: COLOR
            value: "$COLOR"
        ports:
        - containerPort: 5000